Repository mitch7391/homebridge-cmd4-AdvantageAir, pull requests merged in 2022-08, with the labels that each got.

#66 [Pull Request] Auto Config Creator for Cmd4-AdvantageAir
  ConfigCreator.sh
  cmd4Config_AdvAir.sh
Labels: enhancement, pull-request

#67 [Pull Request] ConfigCreator Bug fix for Mac users
  ConfigCreator.sh
Labels: bug, pull-request

#69 [Pull Request] Running ConfigCreator from Custom Homebridge Ui
  ConfigCreator.sh
  config.schema.json
  homebridge-ui/public/index.html
  homebridge-ui/server.js
Labels: enhancement, pull-request

#73 [Pull Request] v3.6.0
  CHANGELOG.md
  ConfigCreator.sh
  package-lock.json
  package.json
Labels: bug, documentation, enhancement, pull-request
