Repository mitch7391/homebridge-cmd4-AdvantageAir, pull requests merged in 2022-02, with the labels that each got.

#36 v3.2.0
  AdvAir.sh
  CHANGELOG.md
  Config_Samples/ConfigSample_NoSensors.json
  Config_Samples/ConfigSample_Sensors.json
  Config_Samples/ConfigSample_SomeSensors.json
  README.md
  homebridge-ui/server.js
  package-lock.json
  package.json
Labels: documentation, enhancement

#37 [Feature] Added support for MyPlace system
  AdvAir.sh
Labels: enhancement

#40 [Pull Request] Some bug fixes
  AdvAir.sh
Labels: bug

#41 [Pull Request] B fix unit tests
  AdvAir.sh
Labels: bug

#42 [Pull Request] B fix unit tests
  AdvAir.sh
Labels: bug

#43 [Pull Request] B fix unit tests
  AdvAir.sh
  test/GetCurrentTemperature.bats
  test/setup
  test/testData/dataOneZone/getSystemData.txt0
Labels: bug

#44 [Pull Request] Script refinement to allow unit tests to run and bugs fix
  AdvAir.sh
  GetCurrentTemperature.bats
  setup
Labels: bug, enhancement

#46 [Pull Request] Make MyPlace Extras independent of aircon system
  AdvAir.sh
Labels: enhancement

#47 [Pull Request] B fix unit tests
  test/GetCurrentTemperature.bats
  test/GetTemperatureDisplayUnits.bats
  test/SetOn.bats
  test/testData/dataOneZone/getSystemData.txt0
Labels: bug

#49 [Pull Request] Streamline the code for multiple zones closing
  AdvAir.sh
Labels: bug

#50 [Pull Request] Multiple Aircon Systems and Ability to Flip Open/Close
  AdvAir.sh
  test/GetBrightness.bats
  test/GetCurrentHeatingCoolingState.bats
  test/GetCurrentTemperature.bats
  test/GetCurrentTemperature.bats_old
  test/GetNoSensors.bats
  test/GetOn.bats
  test/GetStatusLowBattery.bats
  test/GetTargetHeatingCoolingState.bats
  test/GetTargetTemperature.bats
  test/SetOn.bats
  test/compare/AdvAir.sh
  test/testData/dataOneZone/getSystemData.txt0
Labels: enhancement, pull-request

#52 [Pull Request] Bug Fix for `flip` Capability
  AdvAir.sh
Labels: bug, pull-request
